config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users,
              path: :gurus,
              path_names: { sign_in: :login, sign_out: :logout },
              controllers: { sessions: 'sessions' }
  devise_for :admins, path: :admin


  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :feedback, only: [:index, :create]

  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges, except: :show
    
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: :true, except: :index do
        resources :answers, shallow: :true, except: :index
      end
    end
  end
  
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badges_users, dependent: :destroy
  has_many :users, through: :badges_users, dependent: :destroy

  validates :title, :image_url, presence: :true
  validates :rule_subject, uniqueness: { scope: :rule_objective }, inclusion: { in: BadgeService::RULE_SUBJECTS, message: "Badge service doesn't recognize given rule subject." }
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < ApplicationController

  before_action :find_badge, only: [:destroy, :update, :edit]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = current_user.badges.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  def edit; end

  def update
    if @badge.update!(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :image_url, :rule_subject, :rule_objective)
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badges_rules
    BadgeService::RULE_SUBJECTS.map { |rule_subject| [t("badges.rules.#{rule_subject}"), rule_subject] }
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.title %></td>
  <td><%= t("badges.rules.#{badge.rule_subject}") %></td>
  <td><%= badge.rule_objective %></td>
  <td>
    <%= link_to 'Edit', edit_admin_badge_path(badge) %>
  </td>
  <td>
    <%= link_to 'Delete',
        admin_badge_path(badge),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>

<%= render 'shared/errors', resource: @badge %>

<p>
  <%= form.label :title %><br>
  <%= form.text_field :title %>
</p>

<p>
  <%= form.label :image_url %><br>
  <%= form.text_field :image_url %>
</p>

<p>
  <%= form.label :badge_rule_subject %>
  <%= form.select :rule_subject, badges_rules %>
</p>

<p>
  <%= form.label :badge_rule_objective %><br>
  <%= form.text_field :rule_objective %>
</p>

<p><%= form.submit %></p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1>Edit Badge:<%= @badge.title %></h1>

<%= render 'form' %>

<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1>Badges List:</h1>

<p>
  <%= link_to 'New badge', new_admin_badge_path %> | 
  <%= link_to 'To Tests', admin_tests_path %>
</p>

<%= render 'shared/errors', resource: @badge %>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Badge rule</th>
    <th>Badge objective</th>
    <th colspan = "2">Actions</th>
  </tr>
  <%= render @badges %>
</table>

app/views/admin/badges/new.html.erb
<h1>New Badge:</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_badges_path %>