config/routes.rb
Rails.application.routes.draw do

  root to: 'tests#index'

  devise_for :users,
              path: :gurus,
              path_names: { sign_in: :login, sign_out: :logout },
              controllers: { sessions: 'sessions' }
  devise_for :admins, path: :admin


  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :feedback, only: [:index, :create]

  resources :test_passages, only: [:show, :update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges, except: :show
    
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: :true, except: :index do
        resources :answers, shallow: :true, except: :index
      end
    end
  end
  
end

app/models/admin.rb
class Admin < User

  validates :first_name, :last_name, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validate :answers_per_question, on: :create
  validates :body, presence: true

  def answers_per_question
    answers_num = question.answers.count
    errors.add(:answers_max_exceeded, message: 'Question can\'t contain more than 4 answers.') if answers_num >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :badges_users, dependent: :destroy
  has_many :users, through: :badges_users, dependent: :destroy

  validates :title, :image_url, presence: :true
  validates :rule_subject, uniqueness: { scope: :rule_objective }, inclusion: { in: BadgeService::RULE_SUBJECTS, message: "Badge service doesn't recognize given rule subject." }
end

app/models/badges_user.rb
class BadgesUser < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :destroy

  validates :title, presence: :true,
                    uniqueness: :true
end

app/models/feedback.rb
class Feedback
  include ActiveModel::Model

  attr_accessor :email, :content

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :content, presence: true

  def send_mail
    FeedbackMailer.send_feedback(self.email, self.content).deliver_now
  end
end

app/models/gist.rb
class Gist < ApplicationRecord

  validates :gist_url, presence: true

  belongs_to :user
  belongs_to :question

end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :test
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: :true
end

app/models/test.rb
class Test < ApplicationRecord
  has_many :test_passages
  has_many :users, through: :test_passages, dependent: :destroy
  belongs_to :category, optional: true
  belongs_to :user, optional: true
  has_many :questions, dependent: :destroy
  has_many :histories, dependent: :destroy

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..9) }
  scope :insane, -> { where(level: 10..Float::INFINITY) }
  scope :tests_by_level, -> (level) { where(level: level) }
  scope :tests_by_category, -> (category) { joins(:category).where(categories: { title: category }).order(title: :desc).pluck(:title) }

  validates :title, presence: :true, uniqueness: { scope: :level }
  validates :level, numericality: { greater_than_or_equal_to: 0 }
  validates :duration, numericality: { greater_than_or_equal_to: 0 }
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  def accept!(answer_ids)
    if time_remaining > 0
      self.correct_questions += 1 if correct_answer?(answer_ids)
      self.successful = successful?
      save!
    else
      self.current_question = nil
    end
  end

  def completed?
    self.current_question.nil?
  end

  def successful?
    success_rate >= 85
  end

  def success_rate
    self.correct_questions.fdiv(test.questions.count) * 100
  end

  def question_number
    test.questions.order(:id).where('id <= ?', current_question.id).count
  end

  def time_remaining
    (created_at.to_time + test.duration.minutes - Time.now) / 1.second
  end

  private

  def before_validation_set_current_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers_count = correct_answers.count
    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if self.current_question.nil?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :test_passages
  has_many :tests, through: :test_passages
  has_many :created_tests, dependent: :destroy, foreign_key: 'user_id', class_name: 'Test'
  has_many :histories, dependent: :destroy
  has_many :badges_users
  has_many :badges, through: :badges_users, dependent: :destroy

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable

  def tests_by_level(level)
    created_tests.where( { level: level } )
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end

  def full_name
    if admin?
      "#{self.first_name} #{self.last_name}"
    else
      email
    end
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_test, only: :start

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_not_found

  def start
    if @test.questions.count > 0
      current_user.tests.push(@test)
      redirect_to current_user.test_passage(@test)
    end
  end

  def index
    @tests = Test.all
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def rescue_with_not_found
    render 'shared/_page_not_found'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_key_to_bootstrap_class(type)
    { notice: 'alert-info', alert: 'alert-info' }[type.to_sym]
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badges_rules
    BadgeService::RULE_SUBJECTS.map { |rule_subject| [t("badges.rules.#{rule_subject}"), rule_subject] }
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  
  def question_form_header(question)
    if question.persisted?
      "Edit question #{question.body}"
    else
      'Add new question' 
    end
  end

end

app/helpers/tests_helper.rb
module TestsHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    "https://github.com/#{author}/#{repo}"
  end

  def duration_helper(duration)
    if duration.zero?
      t('.duration_unlim') 
    else
      duration
    end
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru Administration panel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav_admin' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Testguru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>

    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2><%= t('.header', count: resource.errors.count) %></h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= flash_key_to_bootstrap_class(key) %>" role="alert">
    <%= sanitize(message) %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<p><%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'https://thinknetica.com', target: '_blank' %></p>

<p>Mikhail Gudyrin <%= current_year %> ©,
  <%= link_to 'GitHub', github_url('gudyrmik', 'testguru'), target: '_blank' %>
</p>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <%= link_to 'Feedback', feedback_index_path %>

  <span class="navbar-text">
    <% if user_signed_in? %>
      Welcome, <b><%= "#{current_user.first_name} #{current_user.last_name}" %></b>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Register', new_user_registration_path %>
    <% end %>
  </span>
</nav>

app/views/shared/_nav_admin.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru Admin Panel', admin_tests_path, class: 'navbar-brand' %>

  <span class="navbar-text">
    <% if user_signed_in? %>
      Welcome, <b><%= "#{current_user.first_name} #{current_user.last_name}" %></b>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Register', new_user_registration_path %>
    <% end %>
  </span>
</nav>

app/views/shared/_page_not_found.html.erb
<p>Page not found</p>
<%= link_to 'Main', tests_path %>